Allow more services traffic through firewall
Looking through UFW logs I found some more traffic that was being
blocked on both the master and worker nodes that was causing problems.

Allow slurmctld on master node: fixes slurm commands on worker node
- master ufw logs: `hpc-master-node kernel: [5374476.444104] [UFW BLOCK] ... PROTO=TCP SPT=54737 DPT=3389 WINDOW=8192 RES=0x00 CWR ECE SYN URGP=0`
- worker slurmd logs: `error: Unable to register: Unable to contact slurm controller (connect failure)`

Allow slurmd on worker node: fixes worker node being set to `DOWN` state
- worker ufw logs: `hpc-worker-02 kernel: [43351.006693] [UFW BLOCK] ... PROTO=TCP SPT=55926 DPT=6818 WINDOW=64240 RES=0x00 SYN URGP=0`
- master slurmctld logs:
```
error: Nodes hpc-worker-02 not responding, setting DOWN
update_node: node hpc-worker-02 state set to IDLE
(deploy)
Node hpc-worker-02 now responding
```

Allow node_exporter on worker node: just saw this was being blocked too
- worker ufw logs: `hpc-worker-02 kernel: [40067.797586] [UFW BLOCK] ... PROTO=TCP SPT=60384 DPT=9100 WINDOW=64240 RES=0x00 SYN URGP=0`